/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iRouteControllerSol from "./IRouteController.sol";
export type { iRouteControllerSol };
import type * as extensions from "./extensions";
export type { extensions };
export type { BaseRouteController } from "./BaseRouteController";
