/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRouteCanReply } from "./IRouteCanReply";
export type { IRouteController } from "./IRouteController";
