/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as beaconSol from "./Beacon.sol";
export type { beaconSol };
export type { BaseERC20 } from "./BaseERC20";
export type { IERC20 } from "./IERC20";
export type { LabzToken } from "./LabzToken";
export type { LabzTokenControllerLogicBeaconProxy } from "./LabzTokenControllerLogicBeaconProxy";
export type { PayableERC20 } from "./PayableERC20";
export type { TokenRouter } from "./TokenRouter";
