/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftEipVersioningSol from "./draft-EIPVersioning.sol";
export type { draftEipVersioningSol };
export type { ERC165 } from "./ERC165";
export type { IERC165 } from "./IERC165";
export type { Payable } from "./Payable";
export type { SafeVars } from "./SafeVars";
