/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface SafeVarsInterface extends utils.Interface {
  functions: {
    "SAFE_ERC20_BALANCE_OF()": FunctionFragment;
    "SAFE_ERC20_DECIMALS_SIG()": FunctionFragment;
    "SAFE_ERC20_NAME_SIG()": FunctionFragment;
    "SAFE_ERC20_SYMBOL_SIG()": FunctionFragment;
    "SAFE_ERC20_TOTALSUPPLY()": FunctionFragment;
    "SAFE_ERC20_TRANSFER()": FunctionFragment;
    "SAFE_ERC20_TRANSFER_FROM()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "SAFE_ERC20_BALANCE_OF"
      | "SAFE_ERC20_DECIMALS_SIG"
      | "SAFE_ERC20_NAME_SIG"
      | "SAFE_ERC20_SYMBOL_SIG"
      | "SAFE_ERC20_TOTALSUPPLY"
      | "SAFE_ERC20_TRANSFER"
      | "SAFE_ERC20_TRANSFER_FROM"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SAFE_ERC20_BALANCE_OF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_ERC20_DECIMALS_SIG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_ERC20_NAME_SIG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_ERC20_SYMBOL_SIG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_ERC20_TOTALSUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_ERC20_TRANSFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_ERC20_TRANSFER_FROM",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "SAFE_ERC20_BALANCE_OF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_ERC20_DECIMALS_SIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_ERC20_NAME_SIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_ERC20_SYMBOL_SIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_ERC20_TOTALSUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_ERC20_TRANSFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_ERC20_TRANSFER_FROM",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SafeVars extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SafeVarsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SAFE_ERC20_BALANCE_OF(overrides?: CallOverrides): Promise<[string]>;

    SAFE_ERC20_DECIMALS_SIG(overrides?: CallOverrides): Promise<[string]>;

    SAFE_ERC20_NAME_SIG(overrides?: CallOverrides): Promise<[string]>;

    SAFE_ERC20_SYMBOL_SIG(overrides?: CallOverrides): Promise<[string]>;

    SAFE_ERC20_TOTALSUPPLY(overrides?: CallOverrides): Promise<[string]>;

    SAFE_ERC20_TRANSFER(overrides?: CallOverrides): Promise<[string]>;

    SAFE_ERC20_TRANSFER_FROM(overrides?: CallOverrides): Promise<[string]>;
  };

  SAFE_ERC20_BALANCE_OF(overrides?: CallOverrides): Promise<string>;

  SAFE_ERC20_DECIMALS_SIG(overrides?: CallOverrides): Promise<string>;

  SAFE_ERC20_NAME_SIG(overrides?: CallOverrides): Promise<string>;

  SAFE_ERC20_SYMBOL_SIG(overrides?: CallOverrides): Promise<string>;

  SAFE_ERC20_TOTALSUPPLY(overrides?: CallOverrides): Promise<string>;

  SAFE_ERC20_TRANSFER(overrides?: CallOverrides): Promise<string>;

  SAFE_ERC20_TRANSFER_FROM(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    SAFE_ERC20_BALANCE_OF(overrides?: CallOverrides): Promise<string>;

    SAFE_ERC20_DECIMALS_SIG(overrides?: CallOverrides): Promise<string>;

    SAFE_ERC20_NAME_SIG(overrides?: CallOverrides): Promise<string>;

    SAFE_ERC20_SYMBOL_SIG(overrides?: CallOverrides): Promise<string>;

    SAFE_ERC20_TOTALSUPPLY(overrides?: CallOverrides): Promise<string>;

    SAFE_ERC20_TRANSFER(overrides?: CallOverrides): Promise<string>;

    SAFE_ERC20_TRANSFER_FROM(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    SAFE_ERC20_BALANCE_OF(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_ERC20_DECIMALS_SIG(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_ERC20_NAME_SIG(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_ERC20_SYMBOL_SIG(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_ERC20_TOTALSUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_ERC20_TRANSFER(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_ERC20_TRANSFER_FROM(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    SAFE_ERC20_BALANCE_OF(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_ERC20_DECIMALS_SIG(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_ERC20_NAME_SIG(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_ERC20_SYMBOL_SIG(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_ERC20_TOTALSUPPLY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_ERC20_TRANSFER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_ERC20_TRANSFER_FROM(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
