/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as routesRegistrySol from "./routesRegistry.sol";
export type { routesRegistrySol };
export type { Router } from "./Router";
export type { RouterOpcodes } from "./RouterOpcodes";
