/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as beaconSol from "./Beacon.sol";
export { BaseERC20__factory } from "./BaseERC20__factory";
export { IERC20__factory } from "./IERC20__factory";
export { LabzToken__factory } from "./LabzToken__factory";
export { LabzTokenControllerLogicBeaconProxy__factory } from "./LabzTokenControllerLogicBeaconProxy__factory";
export { PayableERC20__factory } from "./PayableERC20__factory";
export { TokenRouter__factory } from "./TokenRouter__factory";
